spring:
  application:
    name: Unsafebox API
  r2dbc:
    url: r2dbc:postgresql://postgres-skeleton-db:5432/postgres_rv_database
    username: rv_user
    password: rv_password



#    spring.datasource.initialization-mode=always
#    spring.datasource.driverClassName=org.postgresql.Driver